identifier_name:
    min_length:
        warning: 1
        error: 0

large_tuple:
    warning: 5
    error: 6

colon:
  apply_to_dictionaries: false

opt_in_rules:
  - vertical_whitespace
  - closure_spacing

disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - line_length
  - trailing_comma
  - force_try
