# This workflow fetches the latest configlet binary and lints this repository

name: Configlet

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Fetch configlet
      uses: exercism/github-actions/configlet-ci@master

    - name: Configlet Linter
      run: configlet lint .
