name: Danger + SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/danger.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      - 'Dangerfile'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  lint_danger:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Install bundler and danger gems
      run: sudo gem install bundler && bundle install

    - name: Run SwiftLint and output to lintreport.json
      run: swiftlint lint --quiet --reporter json | tee lintreport.json

    - name: Run Danger to enforce PR guidelines and note SwiftLint results
      uses: MeilCli/danger-action@v5
      with:
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.danger_github_api_token }}
