# This workflow runs the Swift package manager

name: Swift package manager

on:
  pull_request:
    paths:
      - '.github/workflows/package.yml'
      - '**/*.swift'
      - 'config.json'

jobs:
  package_mac:
    runs-on: macos-10.15

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Generate Xcode project
      run: swift package generate-xcodeproj

  package_linux:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Generate Xcode project
      run: swift package generate-xcodeproj
